alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/uut_std.v"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/uut_pli.v"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/dac_sc1.bde"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/lrc.bde"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/adrcnt.bde"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/datreg.v"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/sub.v"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/reg4.v"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/comp.v"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/dat_cnt.v"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/intelhex.v"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/asciidec.v"
alog -dbg -pli "$DSN\src\external\read_byte_ex.dll" "$DSN/src/cd4029.v"
comp "$DSN/src/external/read_byte_ex.dlm"
